/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgentType = { 'travel' : null } |
  { 'trading' : null } |
  { 'general' : null };
export interface MemoryContext {
  'totalQueryCount' : bigint,
  'lastToolCalls' : Array<ToolCall>,
  'recentQueries' : Array<QueryRecord>,
  'activeAgents' : Array<AgentType>,
}
export type QueryId = string;
export interface QueryRecord {
  'toolsUsed' : Array<ToolCall>,
  'queryText' : string,
  'agentType' : AgentType,
  'rawApiResponse' : string,
  'queryId' : QueryId,
  'timestamp' : Timestamp,
  'resultSummary' : string,
}
export interface QueryResult {
  'toolsUsed' : Array<ToolCall>,
  'agentType' : AgentType,
  'rawApiResponse' : string,
  'queryId' : QueryId,
  'timestamp' : Timestamp,
  'resultSummary' : string,
}
export interface QueryStatus {
  'status' : { 'pending' : null } |
    { 'complete' : null } |
    { 'failed' : null },
  'agentType' : [] | [AgentType],
  'queryId' : QueryId,
  'timestamp' : Timestamp,
  'resultSummary' : [] | [string],
}
export type Timestamp = bigint;
export interface ToolCall {
  'output' : string,
  'toolName' : string,
  'input' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'getAgentHistory' : ActorMethod<[string], Array<QueryRecord>>,
  'getMemoryContext' : ActorMethod<[], MemoryContext>,
  'getQueryStatus' : ActorMethod<[string], QueryStatus>,
  'submitQuery' : ActorMethod<[string], QueryResult>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];