/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ToolCall = IDL.Record({
  'output' : IDL.Text,
  'toolName' : IDL.Text,
  'input' : IDL.Text,
});
export const AgentType = IDL.Variant({
  'travel' : IDL.Null,
  'trading' : IDL.Null,
  'general' : IDL.Null,
});
export const QueryId = IDL.Text;
export const Timestamp = IDL.Int;
export const QueryRecord = IDL.Record({
  'toolsUsed' : IDL.Vec(ToolCall),
  'queryText' : IDL.Text,
  'agentType' : AgentType,
  'rawApiResponse' : IDL.Text,
  'queryId' : QueryId,
  'timestamp' : Timestamp,
  'resultSummary' : IDL.Text,
});
export const MemoryContext = IDL.Record({
  'totalQueryCount' : IDL.Nat,
  'lastToolCalls' : IDL.Vec(ToolCall),
  'recentQueries' : IDL.Vec(QueryRecord),
  'activeAgents' : IDL.Vec(AgentType),
});
export const QueryStatus = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'complete' : IDL.Null,
    'failed' : IDL.Null,
  }),
  'agentType' : IDL.Opt(AgentType),
  'queryId' : QueryId,
  'timestamp' : Timestamp,
  'resultSummary' : IDL.Opt(IDL.Text),
});
export const QueryResult = IDL.Record({
  'toolsUsed' : IDL.Vec(ToolCall),
  'agentType' : AgentType,
  'rawApiResponse' : IDL.Text,
  'queryId' : QueryId,
  'timestamp' : Timestamp,
  'resultSummary' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'getAgentHistory' : IDL.Func([IDL.Text], [IDL.Vec(QueryRecord)], ['query']),
  'getMemoryContext' : IDL.Func([], [MemoryContext], ['query']),
  'getQueryStatus' : IDL.Func([IDL.Text], [QueryStatus], ['query']),
  'submitQuery' : IDL.Func([IDL.Text], [QueryResult], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ToolCall = IDL.Record({
    'output' : IDL.Text,
    'toolName' : IDL.Text,
    'input' : IDL.Text,
  });
  const AgentType = IDL.Variant({
    'travel' : IDL.Null,
    'trading' : IDL.Null,
    'general' : IDL.Null,
  });
  const QueryId = IDL.Text;
  const Timestamp = IDL.Int;
  const QueryRecord = IDL.Record({
    'toolsUsed' : IDL.Vec(ToolCall),
    'queryText' : IDL.Text,
    'agentType' : AgentType,
    'rawApiResponse' : IDL.Text,
    'queryId' : QueryId,
    'timestamp' : Timestamp,
    'resultSummary' : IDL.Text,
  });
  const MemoryContext = IDL.Record({
    'totalQueryCount' : IDL.Nat,
    'lastToolCalls' : IDL.Vec(ToolCall),
    'recentQueries' : IDL.Vec(QueryRecord),
    'activeAgents' : IDL.Vec(AgentType),
  });
  const QueryStatus = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'complete' : IDL.Null,
      'failed' : IDL.Null,
    }),
    'agentType' : IDL.Opt(AgentType),
    'queryId' : QueryId,
    'timestamp' : Timestamp,
    'resultSummary' : IDL.Opt(IDL.Text),
  });
  const QueryResult = IDL.Record({
    'toolsUsed' : IDL.Vec(ToolCall),
    'agentType' : AgentType,
    'rawApiResponse' : IDL.Text,
    'queryId' : QueryId,
    'timestamp' : Timestamp,
    'resultSummary' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'getAgentHistory' : IDL.Func([IDL.Text], [IDL.Vec(QueryRecord)], ['query']),
    'getMemoryContext' : IDL.Func([], [MemoryContext], ['query']),
    'getQueryStatus' : IDL.Func([IDL.Text], [QueryStatus], ['query']),
    'submitQuery' : IDL.Func([IDL.Text], [QueryResult], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };