/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface QueryRecord {
    toolsUsed: Array<ToolCall>;
    queryText: string;
    agentType: AgentType;
    rawApiResponse: string;
    queryId: QueryId;
    timestamp: Timestamp;
    resultSummary: string;
}
export interface MemoryContext {
    totalQueryCount: bigint;
    lastToolCalls: Array<ToolCall>;
    recentQueries: Array<QueryRecord>;
    activeAgents: Array<AgentType>;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface QueryResult {
    toolsUsed: Array<ToolCall>;
    agentType: AgentType;
    rawApiResponse: string;
    queryId: QueryId;
    timestamp: Timestamp;
    resultSummary: string;
}
export interface ToolCall {
    output: string;
    toolName: string;
    input: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type QueryId = string;
export interface QueryStatus {
    status: Variant_pending_complete_failed;
    agentType?: AgentType;
    queryId: QueryId;
    timestamp: Timestamp;
    resultSummary?: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum AgentType {
    travel = "travel",
    trading = "trading",
    general = "general"
}
export enum Variant_pending_complete_failed {
    pending = "pending",
    complete = "complete",
    failed = "failed"
}
export interface backendInterface {
    getAgentHistory(agentTypeText: string): Promise<Array<QueryRecord>>;
    getMemoryContext(): Promise<MemoryContext>;
    getQueryStatus(queryId: string): Promise<QueryStatus>;
    submitQuery(queryText: string): Promise<QueryResult>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { AgentType as _AgentType, MemoryContext as _MemoryContext, QueryId as _QueryId, QueryRecord as _QueryRecord, QueryResult as _QueryResult, QueryStatus as _QueryStatus, Timestamp as _Timestamp, ToolCall as _ToolCall } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAgentHistory(arg0: string): Promise<Array<QueryRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentHistory(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentHistory(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemoryContext(): Promise<MemoryContext> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemoryContext();
                return from_candid_MemoryContext_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemoryContext();
            return from_candid_MemoryContext_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQueryStatus(arg0: string): Promise<QueryStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getQueryStatus(arg0);
                return from_candid_QueryStatus_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQueryStatus(arg0);
            return from_candid_QueryStatus_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitQuery(arg0: string): Promise<QueryResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuery(arg0);
                return from_candid_QueryResult_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuery(arg0);
            return from_candid_QueryResult_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_AgentType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgentType): AgentType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_MemoryContext_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemoryContext): MemoryContext {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_QueryRecord_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QueryRecord): QueryRecord {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_QueryResult_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QueryResult): QueryResult {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_QueryStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QueryStatus): QueryStatus {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AgentType]): AgentType | null {
    return value.length === 0 ? null : from_candid_AgentType_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        pending: null;
    } | {
        complete: null;
    } | {
        failed: null;
    };
    agentType: [] | [_AgentType];
    queryId: _QueryId;
    timestamp: _Timestamp;
    resultSummary: [] | [string];
}): {
    status: Variant_pending_complete_failed;
    agentType?: AgentType;
    queryId: QueryId;
    timestamp: Timestamp;
    resultSummary?: string;
} {
    return {
        status: from_candid_variant_n11(_uploadFile, _downloadFile, value.status),
        agentType: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.agentType)),
        queryId: value.queryId,
        timestamp: value.timestamp,
        resultSummary: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.resultSummary))
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    toolsUsed: Array<_ToolCall>;
    agentType: _AgentType;
    rawApiResponse: string;
    queryId: _QueryId;
    timestamp: _Timestamp;
    resultSummary: string;
}): {
    toolsUsed: Array<ToolCall>;
    agentType: AgentType;
    rawApiResponse: string;
    queryId: QueryId;
    timestamp: Timestamp;
    resultSummary: string;
} {
    return {
        toolsUsed: value.toolsUsed,
        agentType: from_candid_AgentType_n4(_uploadFile, _downloadFile, value.agentType),
        rawApiResponse: value.rawApiResponse,
        queryId: value.queryId,
        timestamp: value.timestamp,
        resultSummary: value.resultSummary
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    toolsUsed: Array<_ToolCall>;
    queryText: string;
    agentType: _AgentType;
    rawApiResponse: string;
    queryId: _QueryId;
    timestamp: _Timestamp;
    resultSummary: string;
}): {
    toolsUsed: Array<ToolCall>;
    queryText: string;
    agentType: AgentType;
    rawApiResponse: string;
    queryId: QueryId;
    timestamp: Timestamp;
    resultSummary: string;
} {
    return {
        toolsUsed: value.toolsUsed,
        queryText: value.queryText,
        agentType: from_candid_AgentType_n4(_uploadFile, _downloadFile, value.agentType),
        rawApiResponse: value.rawApiResponse,
        queryId: value.queryId,
        timestamp: value.timestamp,
        resultSummary: value.resultSummary
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalQueryCount: bigint;
    lastToolCalls: Array<_ToolCall>;
    recentQueries: Array<_QueryRecord>;
    activeAgents: Array<_AgentType>;
}): {
    totalQueryCount: bigint;
    lastToolCalls: Array<ToolCall>;
    recentQueries: Array<QueryRecord>;
    activeAgents: Array<AgentType>;
} {
    return {
        totalQueryCount: value.totalQueryCount,
        lastToolCalls: value.lastToolCalls,
        recentQueries: from_candid_vec_n1(_uploadFile, _downloadFile, value.recentQueries),
        activeAgents: from_candid_vec_n8(_uploadFile, _downloadFile, value.activeAgents)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    complete: null;
} | {
    failed: null;
}): Variant_pending_complete_failed {
    return "pending" in value ? Variant_pending_complete_failed.pending : "complete" in value ? Variant_pending_complete_failed.complete : "failed" in value ? Variant_pending_complete_failed.failed : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    travel: null;
} | {
    trading: null;
} | {
    general: null;
}): AgentType {
    return "travel" in value ? AgentType.travel : "trading" in value ? AgentType.trading : "general" in value ? AgentType.general : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QueryRecord>): Array<QueryRecord> {
    return value.map((x)=>from_candid_QueryRecord_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AgentType>): Array<AgentType> {
    return value.map((x)=>from_candid_AgentType_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
